generic-service:
  ingress:
    host: tier-to-delius-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    SENTRY_ENVIRONMENT: dev
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_HMPPS-AUTH_TOKEN-URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/oauth/token
    INTEGRATIONS_TIER_URL: https://hmpps-tier-preprod.hmpps.service.justice.gov.uk
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/issuer
    CRN-STREAMING_TIMEOUT: "21600000"

generic-prometheus-alerts:
  businessHoursOnly: true