# Common values
generic-service:
  productId: HMPPS518
  nameOverride: cosso-and-delius
  serviceAccountName: cosso-and-delius

  image:
    repository: ghcr.io/ministryofjustice/hmpps-probation-integration-services/cosso-and-delius

  ingress:
    tlsSecretName: cosso-and-delius-cert

  namespace_secrets:
    common:
      SPRING_DATASOURCE_URL: DB_URL
      SPRING_LDAP_URLS: LDAP_URL
      SPRING_LDAP_USERNAME: LDAP_USERNAME
      SPRING_LDAP_PASSWORD: LDAP_PASSWORD
    cosso-and-delius-client-credentials:
      OAUTH2_CLIENT-ID: CLIENT_ID
      OAUTH2_CLIENT-SECRET: CLIENT_SECRET
    cosso-and-delius-database:
      SPRING_DATASOURCE_USERNAME: DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: DB_PASSWORD
    cosso-and-delius-sentry:
      SENTRY_DSN: SENTRY_DSN
    cosso-and-delius-queue:
      MESSAGING_CONSUMER_QUEUE: QUEUE_NAME

generic-prometheus-alerts:
  targetApplication: cosso-and-delius

