---
generic-service:
  nameOverride: feature-flags

  replicaCount: 2

  image:
    repository: flipt/flipt
    tag: v1.37.1
    port: 8080

  securityContext:
    runAsUser: 100 # flipt

  env:
    FLIPT_AUTHENTICATION_REQUIRED: 'true'
    FLIPT_AUTHENTICATION_SESSION_DOMAIN: feature-flags.probation-integration.service.justice.gov.uk
    FLIPT_AUTHENTICATION_METHODS_TOKEN_ENABLED: 'true'
    FLIPT_AUTHENTICATION_METHODS_OIDC_ENABLED: 'true'
    FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_AUTH0_REDIRECT_ADDRESS: https://feature-flags.probation-integration.service.justice.gov.uk
    FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_AUTH0_SCOPES: email profile
    FLIPT_META_TELEMETRY_ENABLED: 'false'

  namespace_secrets:
    flipt-client:
      FLIPT_AUTHENTICATION_METHODS_TOKEN_BOOTSTRAP_TOKEN: TOKEN
    auth0:
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_AUTH0_ISSUER_URL: ISSUER_URL
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_AUTH0_CLIENT_ID: CLIENT_ID
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_AUTH0_CLIENT_SECRET: CLIENT_SECRET
    flipt-db:
      FLIPT_DB_URL: URL

  readinessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 5
  livenessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 5

  ingress:
    enabled: true
    host: feature-flags.probation-integration.service.justice.gov.uk
    tlsSecretName: feature-flags-cert

  allowlist:
    groups:
      - internal
      - unilink_staff

generic-prometheus-alerts:
  targetApplication: feature-flags
  alertSeverity: probation-integration-notifications
