database:
  access:
    username_key: /accredited-programmes-and-delius/db-username
    password_key: /accredited-programmes-and-delius/db-password
    tables:
      - audited_interaction
      - contact
      - domain_event
      - enforcement
      - lic_condition
      - lic_condition_transfer
      - rejected_transfer_diary
      - rqmnt
      - rqmnt_transfer

  audit:
    username: AccreditedProgrammesAndDelius
    forename: Accredited Programmes
    surname: Service
