# Default config
spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        query.mutation_strategy: org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy
        timezone.default_storage: NORMALIZE
        hql.bulk_id_strategy:
          persistent:
            create_tables: false
            drop_tables: false
          global_temporary:
            create_tables: false
            drop_tables: false
  ldap:
    base: dc=moj,dc=com
    base-environment:
      java.naming.ldap.derefAliases: never
  security.oauth2.client:
    registration:
      pathfinder-and-delius:
        provider: hmpps-auth
        authorization-grant-type: client_credentials
        client-id: pathfinder-and-delius
        client-secret: pathfinder-and-delius
    provider:
      hmpps-auth:
        token-uri: http://localhost:${wiremock.port}/auth/oauth/token
springdoc.default-produces-media-type: application/json

delius.db.username: PathfinderAndDelius # Should match value in [deploy/database/access.yml].

management.endpoints.web:
  base-path: /
  exposure.include: [ "health", "info" ]

---
# Shared dev/test config
spring.config.activate.on-profile: [ "dev", "integration-test" ]

spring:
  datasource.url: jdbc:h2:file:./dev;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=true;AUTO_SERVER_PORT=9092
  jpa.hibernate.ddl-auto: create-drop
  security.oauth2.resourceserver.jwt.public-key-location: classpath:local-public-key.pub
  ldap.embedded:
    validation.enabled: false
    base-dn: ${spring.ldap.base}

seed.database: true
wiremock.enabled: true
context.initializer.classes: uk.gov.justice.digital.hmpps.wiremock.WireMockInitialiser

logging.level:
  uk.gov.justice.digital.hmpps: DEBUG
  org.hibernate.tool.schema: ERROR
  org.apache.activemq: WARN

---
spring.config.activate.on-profile: integration-test
spring.datasource.url: jdbc:h2:mem:./test;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH

---
spring.config.activate.on-profile: oracle
spring.datasource.url: 'jdbc:tc:oracle:slim-faststart:///XEPDB1'

---
spring.config.activate.on-profile: delius-db
spring:
  datasource:
    url: 'jdbc:oracle:thin:@//localhost:1521/XEPDB1'
    username: delius_pool
    password: NDelius1
  jpa.hibernate.ddl-auto: validate
seed.database: false
delius.db.username: NationalUser
