database:
  access:
    username_key: /community-payback-and-delius/db-username
    password_key: /community-payback-and-delius/db-password
    tables:
      - contact
      - contact_alert
      - enforcement
      - event
      - upw_appointment

  audit:
    username: CommunityPaybackAndDelius
    forename: Community Payback
    surname: Service
