generic-service:
  ingress:
    host: domain-events-and-delius-dev.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    DOMAIN_EVENTS_BASE_URL: domain-events-and-delius-dev.hmpps.service.justice.gov.uk
    SENTRY_ENVIRONMENT: dev
    LOGGING_LEVEL_UK_GOV_DIGITAL_JUSTICE_HMPPS: DEBUG

generic-prometheus-alerts:
  businessHoursOnly: true