generic-service:
  ingress:
    host: risk-assessment-scores-to-delius-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true

  env:
    SENTRY_ENVIRONMENT: preprod

generic-prometheus-alerts:
  businessHoursOnly: true