database:
  access:
    username_key: /assessment-summary-and-delius/db-username
    password_key: /assessment-summary-and-delius/db-password
    tables:
      - audited_interaction
      - contact
      - deregistration
      - domain_event
      - iaps_offender
      - oasys_assessment
      - oasys_assmnt_section_score
      - oasys_sentence_plan
      - oasys_sp_need
      - oasys_sp_text
      - oasys_sp_work_summary
      - offender
      - registration
      - registration_review
      - reg_category_level_history
    sequences:
      - reg_cat_level_history_id_seq
    packages:
      - pkg_triggersupport # for caseload rebuild

  audit:
    username: AssessmentSummaryAndDelius
    forename: Assessment Summary
    surname: Service
