database:
  access:
    username_key: /manage-supervision-and-delius/db-username
    password_key: /manage-supervision-and-delius/db-password
    tables:
      - contact
      - contact_alert
      - offender
      - offender_address
      - audited_interaction
      - document

  audit:
    username: ManageSupervisionAndDelius
    forename: Manage Supervisions
    surname: Service
