database:
  access:
    username_key: /manage-supervision-and-delius/db-username
    password_key: /manage-supervision-and-delius/db-password
    tables:
      - contact

  audit:
    username: ManageSupervisionAndDelius
    forename: Manage Supervisions
    surname: Service
