database:
  access:
    username_key: /offender-events-and-delius/db-username
    password_key: /offender-events-and-delius/db-password
    tables:
      - offender_delta
      - domain_event

  audit:
    username: OffenderEventsAndDelius
    forename: Offender Events
    surname: Service
